name: ci

on:
  pull_request: {}
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    uses: alixinne/github-workflows/.github/workflows/build-go-docker.yml@v1
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write # It's the GH_TOKEN that writes back to the repository, but this is needed for creating a release
      issues: write   # For semantic-release comments
      packages: write # For pushing to docker
    with:
      submodules: recursive
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
